"""Render a generated proposal (the dict produced by engine.generate) to .docx."""
import io
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.section import WD_ORIENT
from knowledge_base import DISCIPLINES

NAVY = RGBColor(0x1F, 0x3A, 0x5F)


def _set_col_widths(table, widths_inches):
    table.autofit = False
    table.allow_autofit = False
    for row in table.rows:
        for idx, w in enumerate(widths_inches):
            row.cells[idx].width = Inches(w)
    for idx, w in enumerate(widths_inches):
        if idx < len(table.columns):
            table.columns[idx].width = Inches(w)


def _shrink_font(table, size=8):
    for row in table.rows:
        for cell in row.cells:
            for p in cell.paragraphs:
                for run in p.runs:
                    run.font.size = Pt(size)


def _shade_cell(cell, hexcolor):
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement('w:shd')
    shd.set(qn('w:fill'), hexcolor)
    tcPr.append(shd)


def build_docx(project, content, version):
    doc = Document()
    section = doc.sections[0]
    section.orientation = WD_ORIENT.LANDSCAPE
    section.page_width, section.page_height = section.page_height, section.page_width
    section.left_margin = section.right_margin = Inches(0.5)
    section.top_margin = section.bottom_margin = Inches(0.6)
    style = doc.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(10.5)

    title = doc.add_heading(f"{project['name']}", level=0)
    title.runs[0].font.color.rgb = NAVY
    sub = doc.add_paragraph(f"Draft proposal v{version} — customer: {project.get('customer') or 'not specified'}")
    sub.runs[0].italic = True
    doc.add_paragraph("Generated by the E2E Harness proposal-drafting prototype (scripted rule-based engine, not an LLM). "
                       "Requires engineering, commercial and management review before issue.").runs[0].italic = True

    domains = ", ".join(d["label"] for d in content["matched_domains"])
    doc.add_heading("Matched scope", level=1)
    doc.add_paragraph(f"Domain(s) detected from inputs: {domains}")
    if content.get("volume_note"):
        doc.add_paragraph(f"Volume mentioned in inputs: {content['volume_note']}")
    if content.get("addon_notes"):
        for note in content["addon_notes"]:
            doc.add_paragraph(f"• {note}")

    doc.add_heading("Contributors on this draft", level=1)
    t = doc.add_table(rows=1, cols=4)
    t.style = "Light Grid Accent 1"
    hdr = t.rows[0].cells
    for i, h in enumerate(["Name", "Role", "Discipline", "Input type"]):
        hdr[i].text = h
    for c in content["contributors"]:
        row = t.add_row().cells
        row[0].text = c["name"]
        row[1].text = c["role"]
        row[2].text = c["discipline"]
        row[3].text = c["input_type"]

    doc.add_heading("Applicable standards (draft — confirm editions before issue)", level=1)
    t = doc.add_table(rows=1, cols=2)
    t.style = "Light Grid Accent 1"
    t.rows[0].cells[0].text = "Standard"
    t.rows[0].cells[1].text = "Why it applies"
    for code, reason in content["standards"]:
        row = t.add_row().cells
        row[0].text = code
        row[1].text = reason
    _set_col_widths(t, [2.8, 7.2])

    doc.add_heading("Work packages and effort by discipline (hours)", level=1)
    cols = ["ID", "Work package"] + DISCIPLINES + ["Total"]
    t = doc.add_table(rows=1, cols=len(cols))
    t.style = "Light Grid Accent 1"
    for i, h in enumerate(cols):
        t.rows[0].cells[i].text = h
    for wp in content["work_packages"]:
        row = t.add_row().cells
        row[0].text = wp[0]
        row[1].text = wp[1]
        for i, h in enumerate(wp[3]):
            row[2 + i].text = str(h)
        row[-1].text = str(sum(wp[3]))
    total_row = t.add_row().cells
    total_row[1].text = "Base total"
    for i, h in enumerate(content["discipline_totals"]):
        total_row[2 + i].text = str(h)
    total_row[-1].text = str(content["base_hours"])
    cont_row = t.add_row().cells
    cont_row[1].text = f"Risk contingency ({content['contingency_pct']}%)"
    cont_row[-1].text = str(content["contingency_hours"])
    grand_row = t.add_row().cells
    grand_row[1].text = "Total with contingency"
    grand_row[-1].text = str(content["total_hours"])

    widths = [0.5, 2.6] + [0.55] * len(DISCIPLINES) + [0.6]
    _set_col_widths(t, widths)
    _shrink_font(t, 8)

    doc.add_heading("Work package scope", level=2)
    for wp in content["work_packages"]:
        p = doc.add_paragraph()
        p.add_run(f"{wp[0]} — {wp[1]}: ").bold = True
        p.add_run(wp[2])

    doc.add_heading("Assumptions", level=1)
    for a in content["assumptions"]:
        doc.add_paragraph(a, style="List Bullet")

    doc.add_heading("Exclusions", level=1)
    for a in content["exclusions"]:
        doc.add_paragraph(a, style="List Bullet")

    doc.add_heading("Risks", level=1)
    t = doc.add_table(rows=1, cols=3)
    t.style = "Light Grid Accent 1"
    for i, h in enumerate(["Risk", "Impact", "Mitigation"]):
        t.rows[0].cells[i].text = h
    for r in content["risks"]:
        row = t.add_row().cells
        for i in range(3):
            row[i].text = r[i]
    _set_col_widths(t, [3.2, 3.2, 3.6])

    doc.add_heading("Open clarification questions for the customer", level=1)
    if content["clarifications"]:
        for q in content["clarifications"]:
            doc.add_paragraph(q, style="List Bullet")
    else:
        doc.add_paragraph("None auto-detected — inputs covered every checked item for the matched domain(s). Still worth a human read.")

    doc.add_paragraph()
    note = doc.add_paragraph("Approval status: DRAFT. Requires technical review, commercial review and management approval before issue.")
    note.runs[0].italic = True

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf
